name: daleelalhurra
description: "A new Flutter project."

publish_to: "none"

version: 1.1.29+29

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  lottie: ^3.3.1
  animate_do: ^4.2.0
  tutorial_coach_mark: ^1.3.0
  shimmer: ^3.0.0

  # Navigation & UI Components
  get: ^4.6.6
  page_transition: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  animated_splash_screen: ^1.3.0
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  percent_indicator: ^4.2.4
  flutter_advanced_switch: ^3.1.0
  card_swiper: ^3.0.1

  # Storage & Data
  get_storage: ^2.1.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0

  # Networking & API
  dio: ^5.8.0+1
  http: ^1.3.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.2

  # Maps (no device location)
  google_maps_flutter: ^2.12.3

  # Media & Camera
  image_picker: ^1.1.2
  video_player: ^2.9.5

  chewie: ^1.11.3

  # Notifications & Communication
  timezone: ^0.10.0
  mailer: ^6.4.1
  toastification: ^3.0.3

  # Utilities
  intl: ^0.20.2
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  app_links: ^6.4.1
  no_screenshot: ^0.3.1
  logger: ^2.5.0

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Development Tools
  device_preview: ^1.2.0
  showcaseview: ^4.0.1
  firebase_core: ^3.15.1
  smooth_page_indicator: ^1.2.1
  preload_page_view: ^0.2.0
  wolt_modal_sheet: ^0.11.0
  firebase_remote_config: ^5.4.7
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  firebase_messaging: ^15.2.9
  tcard: ^1.3.5
  dots_indicator: ^4.0.1
  flutter_html: ^3.0.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  json_serializable: ^6.9.4
  freezed: ^2.5.8
  build_runner: ^2.4.15

  # App Icon
  flutter_launcher_icons: ^0.14.2
  change_app_package_name: ^1.5.0

dependency_overrides:
  analyzer: ^6.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logos/app_logo.png"
  image_path: "assets/logos/app_logo.png"
  min_sdk_version: 21

analyzer:
  errors:
    invalid_annotation_target: ignore
